"""Initial migration with clean models

Revision ID: 0a3c90b830ab
Revises: 
Create Date: 2025-07-25 21:51:56.758110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3c90b830ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('specialization', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('emergency', 'on_time', 'early', 'late', 'walk_in'), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_end_time', sa.DateTime(), nullable=True),
    sa.Column('served', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_table('receipts',
    sa.Column('receipt_id', sa.String(length=200), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('issue_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estimated_wait', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_table('queue')
    op.drop_table('log')
    op.drop_table('patients')
    op.drop_table('doctors')
    # ### end Alembic commands ###
