"""Initial migration

Revision ID: 1dd26917827b
Revises: 
Create Date: 2025-08-01 20:50:07.980092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dd26917827b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['patient_id'])
        batch_op.create_foreign_key(None, 'doctors', ['doctor_id'], ['id'])
        batch_op.drop_column('actor')
        batch_op.drop_column('id')

    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['patient_id'])
        batch_op.create_foreign_key(None, 'doctors', ['doctor_id'], ['id'])

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['patient_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('actor', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
