"""Add session_end_time to Queue

Revision ID: d32646574878
Revises: 
Create Date: 2025-07-23 10:04:20.222171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32646574878'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_column('session_end_time')

    # ### end Alembic commands ###
